[package]
name = "ocaml-interop"
version = "0.5.3" # remember to update html_root_url
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
license = "MIT"
description = "Utilities for Rust and OCaml interoperability"
homepage = "http://github.com/simplestaking/ocaml-interop"
repository = "http://github.com/simplestaking/ocaml-interop"
keywords = ["ocaml", "rust", "ffi", "interop"]
edition = "2018"
exclude = [
    ".github/*",
]

[package.metadata.docs.rs]
features = [ "without-ocamlopt" ]

[dependencies]
ocaml-sys = "^0.19"
static_assertions = "1.1.0"

[features]
default = ["with-ocaml-main"]
with-ocaml-main = []
without-ocamlopt = ["ocaml-sys/without-ocamlopt"]
